// Generated by ReScript, PLEASE EDIT WITH CARE


function partitionMap(arr, proj) {
  var lefts = [];
  var rights = [];
  arr.forEach(function (e) {
        var l = proj(e);
        if (l.TAG === "Left") {
          lefts.push(l._0);
          return ;
        }
        rights.push(l._0);
      });
  return {
          lefts: lefts,
          rights: rights
        };
}

export {
  partitionMap ,
}
/* No side effect */
