// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function fromArray(arr) {
  return Core__Option.map(arr.at(0), (function (head) {
                return [
                        head,
                        arr.slice(1)
                      ];
              }));
}

function toArray(param) {
  return Belt_Array.concatMany([
              [param[0]],
              param[1]
            ]);
}

export {
  fromArray ,
  toArray ,
}
/* No side effect */
