// Generated by ReScript, PLEASE EDIT WITH CARE


function First(Base) {
  var reduce = function (t, param) {
    return t;
  };
  return {
          reduce: reduce
        };
}

function Last(Base) {
  var reduce = function (param, t) {
    return t;
  };
  return {
          reduce: reduce
        };
}

export {
  First ,
  Last ,
}
/* No side effect */
