// Generated by ReScript, PLEASE EDIT WITH CARE

import * as LodashEs from "lodash-es";
import * as ShimsMjs from "./shims.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function groupBy(prim0, prim1) {
  return ShimsMjs.groupBy(prim0, prim1);
}

function headTail(arr) {
  return Core__Option.map(arr.at(0), (function (fst) {
                return [
                        fst,
                        arr.slice(1)
                      ];
              }));
}

function validate(arr, proj) {
  var result = {
    contents: {
      TAG: "Ok",
      _0: []
    }
  };
  arr.forEach(function (e) {
        var match = result.contents;
        var match$1 = proj(e);
        if (match.TAG === "Ok") {
          if (match$1.TAG !== "Ok") {
            result.contents = {
              TAG: "Error",
              _0: [
                match$1._0,
                []
              ]
            };
            return ;
          }
          match._0.push(match$1._0);
          return ;
        }
        if (match$1.TAG === "Ok") {
          return ;
        }
        match._0[1].push(match$1._0);
      });
  return result.contents;
}

var $$Array = {
  groupBy: groupBy,
  headTail: headTail,
  validate: validate
};

function pascalCase(str) {
  var cc = LodashEs.camelCase(str);
  return cc.slice(0, 1).toUpperCase() + cc.slice(1);
}

var $$String = {
  pascalCase: pascalCase
};

function then(a, f) {
  return f(a);
}

export {
  $$Array ,
  $$String ,
  then ,
}
/* lodash-es Not a pure module */
