// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__List from "@rescript/core/src/Core__List.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function fromPaths(paths) {
  return Core__List.fromArray(Object.entries(Core__Option.getOr(paths, {})).map(function (param) {
                  return {
                          TAG: "PrintPath",
                          name: param[0],
                          value: param[1]
                        };
                }));
}

function printPath(path) {
  
}

export {
  fromPaths ,
  printPath ,
}
/* No side effect */
